// e:/2026/medical-billing-hub/backend/src/utils/mailer.ts
import nodemailer from 'nodemailer';

// Define the shape of our lead for the email function
interface EmailLead {
  name: string;
  email: string;
  clinicName?: string;
  monthlyVolume?: string;
  source?: string;
  lastSearch?: string;
}

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: 'ashimads1998@gmail.com',
    pass: 'ypoo lzyb ibel afsd', // 💡 Generated via Google App Passwords
  },
});

export const sendLeadEmail = async (lead: EmailLead): Promise<void> => {
  const mailOptions = {
    from: '"MedBillMaster" <your-business-email@gmail.com>',
    to: 'YOUR-PERSONAL-EMAIL@gmail.com', // ⬅️ Your destination email
    subject: `🚨 NEW LEAD: ${lead.clinicName || 'Inquiry'}`,
    html: `
      <div style="font-family: sans-serif; border: 1px solid #e2e8f0; padding: 20px; border-radius: 12px; max-width: 500px;">
        <h2 style="color: #4f46e5; margin-top: 0;">New Revenue Audit Request</h2>
        <p><strong>Name:</strong> ${lead.name}</p>
        <p><strong>Email:</strong> ${lead.email}</p>
        <p><strong>Clinic:</strong> ${lead.clinicName || 'Not Specified'}</p>
        <p><strong>Monthly Volume:</strong> ${lead.monthlyVolume || 'Standard'}</p>
        <p><strong>Source:</strong> ${lead.source || 'Home Page'}</p>
        <p><strong>Last Search:</strong> ${lead.lastSearch || 'None'}</p>
        <hr style="border: none; border-top: 1px solid #f1f5f9; margin: 20px 0;" />
        <p style="font-size: 11px; color: #94a3b8;">Generated by MedBillMaster OS 2026</p>
      </div>
    `,
  };

  await transporter.sendMail(mailOptions);
};
